### ISSUE TITLE
c++ unusable because of stdargs inlines

### ISSUE THREAD

**Issue by sezero** [adtools/amigaos-cross-toolchain#87] opened 2017-08-05 17:33 UTC
See https://github.com/cahirwpz/amigaos-gcc-2.95.3/issues/8 :
```
$ cat test.c
#include <proto/dos.h>

$ m68k-amigaos-g++ -O2 -Wall -c test.c
In file included from /opt/m68k-amigaos/lib/gcc-lib/m68k-amigaos/2.95.3/../../../../m68k-amigaos/include/../ndk/include/proto/dos.h:13,
                 from test.c:1:
/opt/m68k-amigaos/lib/gcc-lib/m68k-amigaos/2.95.3/../../../../m68k-amigaos/include/../ndk/include/inline/dos.h:157: badly punctuated parameter list in `#define'
/opt/m68k-amigaos/lib/gcc-lib/m68k-amigaos/2.95.3/../../../../m68k-amigaos/include/../ndk/include/inline/dos.h:262: badly punctuated parameter list in `#define'
/opt/m68k-amigaos/lib/gcc-lib/m68k-amigaos/2.95.3/../../../../m68k-amigaos/include/../ndk/include/inline/dos.h:271: badly punctuated parameter list in `#define'
/opt/m68k-amigaos/lib/gcc-lib/m68k-amigaos/2.95.3/../../../../m68k-amigaos/include/../ndk/include/inline/dos.h:372: badly punctuated parameter list in `#define'
/opt/m68k-amigaos/lib/gcc-lib/m68k-amigaos/2.95.3/../../../../m68k-amigaos/include/../ndk/include/inline/dos.h:453: badly punctuated parameter list in `#define'
/opt/m68k-amigaos/lib/gcc-lib/m68k-amigaos/2.95.3/../../../../m68k-amigaos/include/../ndk/include/inline/dos.h:570: badly punctuated parameter list in `#define'
/opt/m68k-amigaos/lib/gcc-lib/m68k-amigaos/2.95.3/../../../../m68k-amigaos/include/../ndk/include/inline/dos.h:687: badly punctuated parameter list in `#define'
```

Either the above bug needs resolving, or sfdc must be taught to generate some
compatible inline for stdargs.

**Comment by sezero** [comment] 2018-01-10 06:05
PING?

**Comment by cahirwpz** [comment] 2018-01-14 09:06
Issue here is a duplicate of https://github.com/cahirwpz/amigaos-gcc-2.95.3/issues/8. Please refer there for further information.

**Closed** 2022-04-05 20:23 UTC
